server:
  port: 8082

#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            user-service:
#              - service-id: user-service-1
#                uri: http://localhost:8081
#              - service-id: user-service-2
#                uri: http://localhost:8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # eureka에 client로 등록
    fetch-registry: true # Service registry list 를 가져오겠다
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/